import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import { execFileSync } from 'node:child_process';
import test from 'node:test';
import { canonicalBytes } from '../../scripts/ops/r24/corrective/canonical-json.mjs';
import { verifyRuleset } from '../../scripts/ops/r24/corrective/post-audit-merge-gate.mjs';
import { createAuditCycleDurableCarrier, verifyAuditCycleDurableCarrier, verifyAuditCycleTerminalArtifact, verifyCertificationSet } from '../../scripts/ops/r24/corrective/post-audit-certification-set.mjs';

const FILE='docs/OPS/R24/CORRECTIVE/POST_AUDIT_CURRENT_CERTIFICATION_SET_V2.json';
const OLD='docs/OPS/R24/CORRECTIVE/POST_AUDIT_CURRENT_CERTIFICATION_SET_V1.json';
const h=(bytes)=>crypto.createHash('sha256').update(bytes).digest('hex');
const load=()=>{const bytes=fs.readFileSync(FILE);return{value:JSON.parse(bytes),fileDigest:h(bytes)}};
const clone=(value)=>structuredClone(value);
const verify=(value,fileDigest=load().fileDigest)=>verifyCertificationSet({value,fileDigest,candidateSha:'HEAD'});
const raw=(file)=>{const bytes=fs.readFileSync(file);return{bytes,value:JSON.parse(bytes),digest:h(bytes)}};
const CRC_TABLE=new Uint32Array(256).map((_,i)=>{let v=i;for(let b=0;b<8;b+=1)v=(v&1)?(0xedb88320^(v>>>1)):(v>>>1);return v>>>0;});
const crc32=(bytes)=>{let v=0xffffffff;for(const byte of bytes)v=CRC_TABLE[(v^byte)&0xff]^(v>>>8);return(v^0xffffffff)>>>0;};
function zip(entries){const locals=[],centrals=[];let offset=0;for(const entry of entries){const name=Buffer.from(entry.name),bytes=Buffer.from(entry.bytes),crc=crc32(bytes);const local=Buffer.alloc(30);local.writeUInt32LE(0x04034b50,0);local.writeUInt16LE(20,4);local.writeUInt32LE(crc,14);local.writeUInt32LE(bytes.length,18);local.writeUInt32LE(bytes.length,22);local.writeUInt16LE(name.length,26);locals.push(local,name,bytes);const central=Buffer.alloc(46);central.writeUInt32LE(0x02014b50,0);central.writeUInt16LE((3<<8)|20,4);central.writeUInt16LE(20,6);central.writeUInt32LE(crc,16);central.writeUInt32LE(bytes.length,20);central.writeUInt32LE(bytes.length,24);central.writeUInt16LE(name.length,28);central.writeUInt32LE((0o100644<<16)>>>0,38);central.writeUInt32LE(offset,42);centrals.push(central,name);offset+=local.length+name.length+bytes.length;}const centralBytes=Buffer.concat(centrals),eocd=Buffer.alloc(22);eocd.writeUInt32LE(0x06054b50,0);eocd.writeUInt16LE(entries.length,8);eocd.writeUInt16LE(entries.length,10);eocd.writeUInt32LE(centralBytes.length,12);eocd.writeUInt32LE(offset,16);return Buffer.concat([...locals,centralBytes,eocd]);}

function terminalFixture(mutator=()=>{}){
  const authorityFile=raw('docs/OPS/R24/CORRECTIVE/POST_AUDIT_CORRECTIONS_OWNER_AMENDMENT_V15.json'),instanceFile=raw('docs/OPS/R24/CORRECTIVE/POST_AUDIT_CORRECTIONS_STAGE_INSTANCE_V16.json'),admissionFile=raw('docs/OPS/R24/CORRECTIVE/POST_AUDIT_CORRECTIONS_STAGE_ADMISSION_ATTESTATION_V16.json'),beforeFile=raw('docs/OPS/R24/CORRECTIVE/AUDIT_CYCLE_1_PROTECTED_WIP_BEFORE_V1.json');
  const candidate='1'.repeat(40),evaluation='2'.repeat(40),tree='3'.repeat(40),certificationEvaluation='4'.repeat(40),certificationTree='5'.repeat(40);
  const certificationValue={evaluationSha:certificationEvaluation,evaluationTreeSha:certificationTree,stageCount:33,artifactBindingDenominator:137},certificationBytes=canonicalBytes(certificationValue),certificationFile={bytes:certificationBytes,value:certificationValue,digest:h(certificationBytes)};
  const ruleset={id:12270444,name:'protect-main',target:'branch',enforcement:'active',conditions:{ref_name:{exclude:[],include:['~DEFAULT_BRANCH']}},bypass_actors:[],rules:[{type:'deletion'},{type:'non_fast_forward'},{type:'pull_request',parameters:{allowed_merge_methods:['merge','squash','rebase'],dismiss_stale_reviews_on_push:true,require_code_owner_review:false,require_extra_approval_for_unattributed_changes:true,require_last_push_approval:false,required_approving_review_count:0,required_review_thread_resolution:true,required_reviewers:[]}},{type:'required_status_checks',parameters:{do_not_enforce_on_create:false,required_status_checks:[{context:'merge-gate',integration_id:15368}],strict_required_status_checks_policy:false}}]},rulesetBytes=Buffer.from(`${JSON.stringify(ruleset)}\n`),rulesetEvidenceFile={bytes:rulesetBytes,value:ruleset,digest:h(rulesetBytes)},rulesetResult=verifyRuleset(ruleset);
  const candidateCi={id:81,status:'completed',conclusion:'success',head_sha:candidate},candidateCiBytes=Buffer.from(`${JSON.stringify(candidateCi)}\n`),candidateCiEvidenceFile={bytes:candidateCiBytes,value:candidateCi,digest:h(candidateCiBytes)};
  const postmergeCi={id:82,status:'completed',conclusion:'success',head_sha:evaluation},postmergeCiBytes=Buffer.from(`${JSON.stringify(postmergeCi)}\n`),postmergeCiEvidenceFile={bytes:postmergeCiBytes,value:postmergeCi,digest:h(postmergeCiBytes)};
  const member={schemaVersion:'AUDIT_CYCLE_1_TERMINAL_ATTESTATION_V1',attestationType:'EXTERNAL_IMMUTABLE_ACCEPTANCE_BOUND_TERMINAL_ATTESTATION',result:'PASS',stageId:'AUDIT_CYCLE_1_CORRECTIONS',externalSourcePlanDigest:'1f5b5b7b63a9f7806db1ecbcd8fa5f16484a73df3fe51f9a5d699d52f4c3fb9a',compiledProgramFileDigest:'da754a8a0e2c09014f342b908502e83ab975488ab665feb2a8a66d0b0d46ae0a',authorityDigest:authorityFile.digest,stageInstanceDigest:instanceFile.digest,stageAdmissionDigest:admissionFile.digest,writeSetDigest:admissionFile.value.writeSetDigest,commandScopeDigest:admissionFile.value.commandScopeDigest,acceptanceSignalsDigest:admissionFile.value.acceptanceSignalsDigest,certificationSetDigest:certificationFile.digest,certificationEvaluationSha:certificationEvaluation,certificationEvaluationTreeSha:certificationTree,certificationStageCount:33,certificationArtifactBindingDenominator:137,protectedWipBeforeCarrierDigest:beforeFile.digest,protectedWipBeforeSnapshotDigest:beforeFile.value.snapshot.snapshotSha256,protectedWipBeforeCompleteDenominator:251,protectedWipBeforeDirtyDenominator:7,liveRuleset:{rulesetId:12270444,returnedBytesDigest:rulesetEvidenceFile.digest,returnedByteLength:rulesetBytes.length,normalizedRulesetDigest:rulesetResult.normalizedRulesetDigest,requiredContexts:rulesetResult.requiredContexts,protections:rulesetResult.protections},predecessorPullRequests:{pr1776:{candidateSha:'77354cfe994588dc1771f3eded29d1e7e68d703f',mergeSha:'af0bfb704c13b0195c12b0144415f2e769f99752'},pr1777:{candidateSha:'bf3d21072879d276ca3489b0bbead780fb39f596',mergeSha:'0a8837ae8b0724fa9c258d98281cae693ce0693e'}},correctionDelivery:{implementationCandidateSha:candidate,implementationMergeSha:evaluation,evaluationSha:evaluation,evaluationTreeSha:tree,candidateCiRunId:81,candidateCiBytesDigest:candidateCiEvidenceFile.digest,exactPostmergeCiRunId:82,exactPostmergeCiBytesDigest:postmergeCiEvidenceFile.digest},repository:'KirPonomarev/writer-editor',workflowPath:'.github/workflows/r24-audit-cycle1-terminal-attestation.yml',workflowRunId:83,runAttempt:1,event:'workflow_dispatch',ref:'refs/heads/main',artifactName:'r24-audit-cycle1-terminal-attestation',artifactFile:'audit-cycle1-terminal-attestation.json',nonRecursiveCarrierPattern:true,programDoneClaimed:false,mainProductGraphNodeStarted:false};
  const subject={member,authorityFile,instanceFile,admissionFile,certificationFile,beforeFile,rulesetEvidenceFile,candidateCiEvidenceFile,postmergeCiEvidenceFile,runEvidenceFile:{value:{id:83,run_attempt:1,status:'completed',conclusion:'success',event:'workflow_dispatch',head_sha:evaluation,head_branch:'main',path:'.github/workflows/r24-audit-cycle1-terminal-attestation.yml',repository:{full_name:'KirPonomarev/writer-editor'}}},artifactEvidence:{id:84,name:'r24-audit-cycle1-terminal-attestation',expired:false,digest:'',workflow_run:{id:83}},git:(args,options={})=>{let value='';if(args[0]==='rev-parse'&&args[1]===`${evaluation}^{tree}`)value=tree;else if(args[0]==='rev-parse'&&args[1]===`${evaluation}^2`)value=candidate;else if(args[0]==='merge-base')value='';else throw new Error(`UNEXPECTED_GIT:${args.join(':')}`);return options.encoding==='utf8'?`${value}\n`:Buffer.from(`${value}\n`);}};
  subject.runEvidenceFile.bytes=canonicalBytes(subject.runEvidenceFile.value);subject.runEvidenceFile.digest=h(subject.runEvidenceFile.bytes);mutator(subject);const memberBytes=canonicalBytes(subject.member);subject.zipBytes=zip([{name:'audit-cycle1-terminal-attestation.json',bytes:memberBytes}]);subject.artifactEvidence.digest=`sha256:${h(subject.zipBytes)}`;return subject;
}

test('successor hashes the complete 137-binding denominator from one exact evaluation identity',()=>{const file=load();const result=verify(file.value,file.fileDigest);assert.equal(result.status,'PASS');assert.equal(result.stageCount,33);assert.equal(result.artifactBindingDenominator,137);});
test('historical false-green is reproduced as exactly nine Git-object mismatches',()=>{const value=JSON.parse(fs.readFileSync(OLD));let denominator=0,mismatches=0;for(const stage of value.stages)for(const binding of stage.artifactBindings){denominator+=1;const bytes=execFileSync('git',['show',`${value.evaluationSha}:${binding.path}`]);if(h(bytes)!==binding.sha256)mismatches+=1;}assert.equal(denominator,137);assert.equal(mismatches,9);});
test('declared artifact mismatch fails closed',()=>{const file=load(),mutant=clone(file.value);mutant.stages[0].artifactBindings[0].sha256='0'.repeat(64);assert.throws(()=>verify(mutant),/E_ARTIFACT_DIGEST_MISMATCH/);});
test('missing artifact fails closed',()=>{const file=load(),mutant=clone(file.value);mutant.stages[0].artifactBindings[0].path='missing/audit-cycle-one-artifact.json';assert.throws(()=>verify(mutant),/E_ARTIFACT_MISSING/);});
test('missing binding cannot shrink the complete denominator',()=>{const file=load(),mutant=clone(file.value);mutant.stages[0].artifactBindings.pop();assert.throws(()=>verify(mutant),/E_ARTIFACT_DENOMINATOR/);});
test('stale tree identity fails closed',()=>{const file=load(),mutant=clone(file.value);mutant.evaluationTreeSha='0'.repeat(40);assert.throws(()=>verify(mutant),/E_EVALUATION_TREE/);});
test('future top-level evaluation cannot retain stale per-stage identities',()=>{const file=load(),mutant=clone(file.value);mutant.evaluationSha=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();mutant.evaluationTreeSha=execFileSync('git',['rev-parse','HEAD^{tree}'],{encoding:'utf8'}).trim();assert.throws(()=>verify(mutant),/E_STAGE_EVALUATION/);});
test('post-evaluation exception is exact and machine checked',()=>{const file=load(),mutant=clone(file.value);mutant.postEvaluationCarrierException.allowedPaths=[];assert.throws(()=>verify(mutant),/E_CARRIER_EXCEPTION_PATHS/);});
test('source-plan byte roles cannot be conflated',()=>{const file=load(),mutant=clone(file.value);mutant.compiledProgramFileDigest=mutant.externalSourcePlanDigest;assert.throws(()=>verify(mutant),/E_SOURCE_PLAN_ROLE_BINDING/);});
test('external audit-cycle terminal ZIP binds admission certification ruleset CI and protected WIP evidence',()=>{const subject=terminalFixture();const result=verifyAuditCycleTerminalArtifact(subject);assert.equal(result.verification.status,'VERIFIED');const carrier=createAuditCycleDurableCarrier({zipBytes:subject.zipBytes,memberBytes:result.memberBytes,runEvidenceFile:subject.runEvidenceFile,artifactEvidence:subject.artifactEvidence,verification:result.verification});const bytes=canonicalBytes(carrier);assert.equal(verifyAuditCycleDurableCarrier({value:carrier,fileDigest:h(bytes)}).status,'VERIFIED');});
test('external verifier preserves role-relative raw ruleset bytes while requiring one normalized semantic view',()=>{const subject=terminalFixture();subject.rulesetEvidenceFile.value.current_user_can_bypass='never';subject.rulesetEvidenceFile.bytes=Buffer.from(`${JSON.stringify(subject.rulesetEvidenceFile.value)}\n`);subject.rulesetEvidenceFile.digest=h(subject.rulesetEvidenceFile.bytes);const result=verifyAuditCycleTerminalArtifact(subject);assert.equal(result.verification.status,'VERIFIED');assert.notEqual(result.verification.terminalRulesetReturnedBytesDigest,result.verification.verificationRulesetReturnedBytesDigest);assert.equal(result.verification.normalizedRulesetDigest,subject.member.liveRuleset.normalizedRulesetDigest);});
test('external verifier rejects a terminal ruleset semantic substitution despite valid raw-digest shape',()=>{assert.throws(()=>verifyAuditCycleTerminalArtifact(terminalFixture((subject)=>{subject.member.liveRuleset.normalizedRulesetDigest='0'.repeat(64);})),/E_LIVE_RULESET_BINDING/);});
test('external audit-cycle terminal verification rejects source-role and CI-byte substitution',()=>{assert.throws(()=>verifyAuditCycleTerminalArtifact(terminalFixture((subject)=>{subject.member.compiledProgramFileDigest=subject.member.externalSourcePlanDigest;})),/E_SOURCE_PLAN_ROLE_BINDING/);assert.throws(()=>verifyAuditCycleTerminalArtifact(terminalFixture((subject)=>{subject.member.correctionDelivery.candidateCiBytesDigest='0'.repeat(64);})),/E_CANDIDATE_CI_BINDING/);});
test('audit-cycle durable carrier rejects modified member bytes',()=>{const subject=terminalFixture(),result=verifyAuditCycleTerminalArtifact(subject),carrier=createAuditCycleDurableCarrier({zipBytes:subject.zipBytes,memberBytes:result.memberBytes,runEvidenceFile:subject.runEvidenceFile,artifactEvidence:subject.artifactEvidence,verification:result.verification});carrier.member.canonicalBase64=Buffer.from('{}\n').toString('base64');assert.throws(()=>verifyAuditCycleDurableCarrier({value:carrier,fileDigest:'0'.repeat(64)}),/E_DURABLE_MEMBER/);});
