export type CoreCommandType = string;

export const CORE_COMMANDS = [
  'project.create',
  'project.applyTextEdit',
  'atlas.entity.create',
  'atlas.alias.add',
  'atlas.mention.confirm',
  'atlas.observation.suppress',
  'atlas.entity.merge',
  'atlas.entity.splitRestore',
  'atlas.observation.reassign',
  'atlas.evidence.reattach',
  'atlas.savedQuery.save',
  'atlas.languageTag.set',
  'atlas.languageTag.clear',
  'atlas.seriesPortability.apply',
  'atlas.seriesPortability.rollback',
  'atlas.calendar.define',
  'atlas.sceneTemporalAnchor.set',
  'atlas.continuityFact.record',
  'idea.create',
  'idea.originLink.add',
  'meaning.promote',
  'manualMap.create',
  'manualMap.node.add',
  'manualMap.node.update',
  'manualMap.node.delete',
  'manualMap.edge.add',
  'manualMap.edge.update',
  'manualMap.edge.delete',
  'manualMap.group.create',
  'manualMap.group.update',
  'manualMap.group.delete',
  'manualMap.attachment.add',
  'manualMap.portal.add',
  'manualMap.template.apply',
  'manualMap.export.json',
  'manualMap.export.imagePdf',
  'manualMap.import.jsonRepeat',
] as const;
export const CORE_EVENTS = [
  'SceneChanged',
  'SceneOrderChanged',
  'EntityCreated',
  'EntityMerged',
  'EntitySplit',
  'AliasChanged',
  'MapChanged',
  'MapNodePromoted',
  'DecisionCommitted',
  'CalendarChanged',
  'TimeRangeChanged',
  'ContinuityDecisionCommitted',
  'ProjectionInvalidated',
  'DerivedGenerationPublished',
  'DerivedGenerationRejectedAsStale',
  'LanguageCapabilityChanged',
  'MigrationPrepared',
  'MigrationCommitted',
  'MigrationRolledBack',
] as const;
export type CoreEventType = (typeof CORE_EVENTS)[number];
